ORIGINAL_PIPE_DISTANCE = 300
ORIGINAL_PIPE_SPEED = 2


SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
GRAVITY = 0.25
PIPE_SPEED = ORIGINAL_PIPE_SPEED
PIPE_GAP = 220
PIPE_DISTANCE = ORIGINAL_PIPE_DISTANCE
PIPE_WIDTH = 100
BIRD_DIMENSION = 50
FLAP_DISTANCE = 50
VELOCITY_AFTER_FLAP = -7

def set_d_p(d_p:int):
    global PIPE_DISTANCE
    PIPE_DISTANCE = d_p

def set_speed(speed:int):
    global PIPE_SPEED
    PIPE_SPEED = speed


